Assignment/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myApps.urls'))
]

myApps/urls.py
from django.urls import path
from . import views

app_name = 'myApps'


urlpatterns = [
    path('', views.list_view, name='list'),
    path('create/', views.create_list, name='create'),
    path('update/<int:pk>/', views.update_list, name='update'),
    path('delete/<int:pk>/', views.delete_list, name='delete'),
    path('graph/', views.visualization_view, name='graph'),
]

myApps/models.py
from django.db import models

# Create your models here.

class CustomerOrderDetails(models.Model):
    customer = models.CharField(max_length=200)
    products = models.CharField(max_length=200)
    order_sales = models.IntegerField(default=0)
    order_units = models.IntegerField(default=0)

    def __str__(self):
        return self.customer

myApps/forms.py
from django import forms
from .models import CustomerOrderDetails

class CustomerOrderDetailsForm(forms.ModelForm):
    class Meta:
        model = CustomerOrderDetails
        fields = '__all__'
        

myApps/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import CustomerOrderDetails
from .forms import CustomerOrderDetailsForm
from . import utils
# Create your views here.


def list_view(request):
    data = CustomerOrderDetails.objects.all()
    context = {
        'data': data
    }
    return render(request, 'myApps/list.html', context=context)

def create_list(request):
    form = CustomerOrderDetailsForm()
    if request.method == 'POST':
        form = CustomerOrderDetailsForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    context = {
        'form': form,
    }
    return render(request, 'myApps/create.html', context=context)

def update_list(request, pk):
    obj = CustomerOrderDetails.objects.get(pk=pk)
    form = CustomerOrderDetailsForm(instance=obj)
    if request.method == 'POST':
        form = CustomerOrderDetailsForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    context = {
        'form': form,
    }
    return render(request, 'myApps/update.html', context=context)

def delete_list(request, pk):
    obj = CustomerOrderDetails.objects.get(pk=pk)
    obj.delete()
    return HttpResponseRedirect('/')

def visualization_view(request):
    obj = CustomerOrderDetails.objects.all()
    x = [x.order_sales for x in obj]
    y = [y.order_units for y in obj]
    chart = utils.get_plot(x, y)
    context = {
        'chart': chart,
    }
    return render(request, 'myApps/visualize.html', context=context)

myApps/templates/myApps/create.html
{% extends "myApps/home.html" %}

{% block title %}
  <title>Create List</title>
{% endblock title %}

{% block content %}
  
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Create</button>
    </form>

{% endblock content %}

myApps/templates/myApps/delete.html
{% extends "myApps/home.html" %}

{% block title %}
  <title>Delete Item</title>
{% endblock title %}

{% block content %}
  <h3>Are you sure waned to delete !!</h3>


{% endblock content %}

myApps/templates/myApps/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title></title>
    {% endblock title %}
</head>
<body>
    <h1>Customer Details</h1>
    
    {% block content %}
      
    {% endblock content %}

    <!-- <a href="">Show</a> &nbsp; -->
    
</body>
</html>

myApps/templates/myApps/list.html
{% extends "myApps/home.html" %}

{% block title %}
  <title>List</title>
{% endblock title %}


{% block content %}

<a href="{% url 'myApps:create'%}"><button type="submit">Create New List</button></a>
<a href="{% url 'myApps:graph'%}"><button type="submit">Graphical View</button></a>

{% for data in data %}
    <hr>
      <ul>
          <li>Customer ID: {{data.id}}</li> 
          <li>Customer: {{data.customer}}</li>
          <li>Products: {{data.products}}</li>
          <li>Sales_Order: {{data.order_sales}}</li>
          <a href="{% url 'myApps:update' data.id%}"><button type="submit">Update</button></a>
          <a href="{% url 'myApps:delete' data.id%}"><button type="submit">Delete</button></a>
          
        
      </ul>
    {% endfor %}
{% endblock content %}

myApps/templates/myApps/update.html
{% extends "myApps/home.html" %}

{% block title %}
  <title>update List</title>
{% endblock title %}


{% block content %}
  
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Update</button>
</form>

{% endblock content %}

myApps/templates/myApps/visualize.html
{% extends "myApps/home.html" %}

{% block title %}
  <title>Graph</title>
{% endblock title %}

{% block content %}

<a href="/"><button type="submit">Back to Main View</button></a>

    {% if chart %}
      <img src="data:image/png; base64, {{chart|safe}}" alt="" srcset="">
    {% endif %}

{% endblock content %}